services:
  postgres:
    image: postgres:15-alpine
    container_name: iso_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro"
    ports:
      - "5432:5432"