version: '3.6'

services:
  postgres:
    image: postgres:15-alpine
    container_name: iso_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "test"
    volumes:
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-database.sh"
      - "./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    ports:
      - "5432:5432"
